spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authentication-route
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/authentication/**