spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 1800
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authentication-route
          uri: lb://user-management-service
          predicates:
            - Path=/api/v1/authentication/**
        - id: user-registration-route
          uri: lb://user-management-service
          predicates:
            - Path=/api/v1/users/**
        - id: chat-route
          uri: lb://chat-service
          predicates:
            - Path=/app/**, /chat/**, /topic/**