version: "3.9"
name: "Make me a cube"
services:
  makemeacube-mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: "makemeacube-admin"
      MYSQL_PASSWORD: "5gQ60AsRB9QbL5rA"
      MYSQL_ROOT_PASSWORD: "t1KEMbMEWX8urV1K"
    ports:
      - "3306:3306"
    volumes:
      - makemeacube-mysql:/var/lib/mysql
volumes:
  makemeacube-mysql:
    external: true