-- MySQL Script generated by MySQL Workbench
-- Sat Nov 26 18:01:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema makemeacube
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `makemeacube` ;

-- -----------------------------------------------------
-- Schema makemeacube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `makemeacube` DEFAULT CHARACTER SET utf8 ;
USE `makemeacube` ;

-- -----------------------------------------------------
-- Table `makemeacube`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `makemeacube`.`User` ;

CREATE TABLE IF NOT EXISTS `makemeacube`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(255) NOT NULL,
  `pseudo` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstName` VARCHAR(255) NULL,
  `lastName` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `isMaker` TINYINT(1) NOT NULL DEFAULT 0,
  `provider` VARCHAR(255) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
